
on:
  pull_request:
    types: [closed]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Test-refs
        shell: bash
        run: | 
          echo "GH SHA: ${GITHUB_SHA}"
          echo "ref: ${GITHUB_REF}"