
on:
  push:

jobs:
  tag_release:
    name: Tagging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release-test'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '10'
          
      - name: Create Tag 
        env:
          GH_PAT: ${{secrets.GH_PAT}}
          REPO: coding-dojo
        run: |
          chmod a+x .github/scripts/tag-and-release.sh
          .github/scripts/tag-and-release.sh
